version: '2.2'
services:
  app:
    build: .
    ports:
      - '8080:8080'  # приложенька слушает 5000 порт, снаружи люди смогут заходить по порту 3337
    stop_grace_period: 3s  # сколько времени пройдёт между запросом на остановку сервиса и жёстким его убийством через SIGKILL
    mem_limit: 1G  # лимит оперативки (не считая своп)
    memswap_limit: 1G  # общий лимит оперативка + своп
    cpu_count: 1  # сколько ядер может использовать сервис
    pids_limit: 128  # сколько процессов может спавнить сервис (защищает от форкбомб!)
    ulimits:
      nofile:  # сколько файловых дескрипторов может открыть сервис
        soft: 8192
        hard: 8192
    restart: always  # всегда поднимать упавший сервис